// Generated by scripts/generate-module-registry.mjs. Do not edit.
import { coreModuleManifest as manifest_core } from '@fonat/core-module';
import { mathModuleManifest as manifest_math } from '@fonat/math-module';
import { projectsModuleManifest as manifest_projects } from '@fonat/projects-module';

export const generatedInstalledModules = [manifest_core, manifest_math, manifest_projects] as const;
